<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Homeautomation\Module'                                      => __DIR__ . '/Module.php',
    'Homeautomation\Controller\CronController'                   => __DIR__ . '/src/Homeautomation/Controller/CronController.php',
    'Homeautomation\Controller\HomeautomationController'         => __DIR__ . '/src/Homeautomation/Controller/HomeautomationController.php',
    'Homeautomation\Model\Socket'                                => __DIR__ . '/src/Homeautomation/Model/Socket.php',
    'Homeautomation\Model\SocketTable'                           => __DIR__ . '/src/Homeautomation/Model/SocketTable.php',
    'Homeautomation\Model\RestApi'                               => __DIR__ . '/src/Homeautomation/Model/RestApi.php',
    'HomeautomationTest\Bootstrap'                               => __DIR__ . '/test/Bootstrap.php',
    'HomeautomationTest\Controller\HomeautomationControllerTest' => __DIR__ . '/test/HomeautomationTest/Controller/HomeautomationControllerTest.php',
);
