<?php $this->headTitle($this->translate('Overview')); ?>
<h1><?php echo $this->escapeHtml($this->translate('Overview')); ?></h1>

<form id="index-form">
	<div class="form-group">
		<div class="container-fluid" id="sockets">
			<div class="row">
				<label for="socket_1_off">Socket 1:</label>
				<button type="button" id="socket_1_off" class="btn btn-default">Off</button>
				<button type="button" id="socket_1_on" class="btn btn-primary">On</button>
			</div>
			<div class="row">
				<label for="socket_2_off">Socket 2:</label>
				<button type="button" id="socket_2_off" class="btn btn-default">Off</button>
				<button type="button" id="socket_2_on" class="btn btn-primary">On</button>
			</div>
			<div class="row">
				<label for="socket_3_off">Socket 3:</label>
				<button type="button" id="socket_3_off" class="btn btn-default">Off</button>
				<button type="button" id="socket_3_on" class="btn btn-primary">On</button>
			</div>
			<div class="row">
				<label for="socket_4_off">Socket 4:</label>
				<button type="button" id="socket_4_off" class="btn btn-default">Off</button>
				<button type="button" id="socket_4_on" class="btn btn-primary">On</button>
			</div>
			<div class="row">
				<label for="socket_5_off">Socket 5:</label>
				<button type="button" id="socket_5_off" class="btn btn-default">Off</button>
				<button type="button" id="socket_5_on" class="btn btn-primary">On</button>
			</div>
			<div class="row">
				<label for="socket_6_off">Socket 6:</label>
				<button type="button" id="socket_6_off" class="btn btn-default">Off</button>
				<button type="button" id="socket_6_on" class="btn btn-primary">On</button>
			</div>
		</div>
	</div>
</form>
<script type="text/javascript">
$(function() {
	$('#sockets button.btn').click(function() {
		var buttonInfo = $(this).attr('id').split('_');
		$.ajax({
			url: "test.html",
			data: { socket: buttonInfo[1], location: buttonInfo[2] }
		}).done(function() {
            BootstrapDialog.show({
                type: BootstrapDialog.TYPE_SUCCESS,
                title: 'Sucess',
                message: 'Socket "' + buttonInfo[1] + '" was powered ' + buttonInfo[2],
            });     
		}).fail(function() {
            BootstrapDialog.show({
                type: BootstrapDialog.TYPE_WARNING,
                title: 'Error',
                message: 'Socket "' + buttonInfo[1] + '" could not be powered ' + buttonInfo[2],
            });     
		})
	});
});
</script>