<?php $this->headTitle($this->translate('Sockets')); ?>
<h1><?php echo $this->translate('Sockets'); ?></h1>
<table class="table" id="sockets">
	<thead>
		<tr>
			<th><?php echo $this->translate('Label'); ?></th>
			<th><?php echo $this->translate('Action'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->sockets as $socket): ?>
			<tr>
				<td><label><?php echo $this->escapeHtml($socket->label);?></label></td>
				<td>
					<button type="button" id="socket_<?php echo $socket->id ?>_off" class="btn <?php if(!$socket->current_status): ?>btn-primary<?php else: ?>btn-default<?php endif ?>"><?php echo $this->translate('Off') ?></button>
					<button type="button" id="socket_<?php echo $socket->id ?>_on" class="btn <?php if($socket->current_status): ?>btn-primary<?php else: ?>btn-default<?php endif ?>"><?php echo $this->translate('On') ?></button>
				</td>
			</tr>
		<?php endforeach ?>
	</tbody>
</table>
<script type="text/javascript">
var ajaxUrl = '<?php echo $this->url('homeautomation', array('action' => 'ajax')) ?>';
var lang = {
	error: '<?php echo $this->translate('Error') ?>',
	errormessage: '<?php echo $this->translate('Socket status could not be changed.') ?>',
	httperrormessage: '<?php echo $this->translate('Request failed.') ?>'
}
</script>