<?php $this->headTitle($this->translate('Sysinfo')); ?>
<h1><?php echo $this->translate('Sysinfo'); ?></h1>
<table class="table" id="sysinfo">
	<thead>
		<tr>
			<th><?php echo $this->translate('Label'); ?></th>
			<th><?php echo $this->translate('Action'); ?></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><label for="btn_temperature"><?php echo $this->translate('Temperature'); ?></label></td>
			<td>
				<button type="button" id="btn_temperature" class="btn btn-default" data-loading-text="<?php echo $this->translate('measuring...'); ?>" autocomplete="off"><?php echo $this->temperature ?> &deg;C</button>
			</td>
		</tr>
	</tbody>
</table>
<script type="text/javascript">
var ajaxUrl = '<?php echo $this->url('homeautomation', array('action' => 'ajax')) ?>';
var lang = {
	error: '<?php echo $this->translate('Error') ?>',
	errormessage: '<?php echo $this->translate('Temperature could not be measured.') ?>',
	httperrormessage: '<?php echo $this->translate('Request failed.') ?>'
}
</script>